// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDt0BqIpGfmQ53IyS3SEqN0BTXMnQ-JHk',
    appId: '1:672372083867:web:b4ded8af88fca2034b0a3e',
    messagingSenderId: '672372083867',
    projectId: 'dano-v2',
    authDomain: 'dano-v2.firebaseapp.com',
    storageBucket: 'dano-v2.firebasestorage.app',
    measurementId: 'G-3LLJJ63LLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKM5CYgNKSao1GyUNEWcU5UYBD6liWKEg',
    appId: '1:672372083867:android:64c3377aa0a997554b0a3e',
    messagingSenderId: '672372083867',
    projectId: 'dano-v2',
    storageBucket: 'dano-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaosqoXb_DU1xyBl9lIaVdO1tVR2ROM2c',
    appId: '1:672372083867:ios:e6183db43941e1584b0a3e',
    messagingSenderId: '672372083867',
    projectId: 'dano-v2',
    storageBucket: 'dano-v2.firebasestorage.app',
    iosClientId: '672372083867-cnnas3gts1gdvu0shv07j92c4u8dfkq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaosqoXb_DU1xyBl9lIaVdO1tVR2ROM2c',
    appId: '1:672372083867:ios:e6183db43941e1584b0a3e',
    messagingSenderId: '672372083867',
    projectId: 'dano-v2',
    storageBucket: 'dano-v2.firebasestorage.app',
    iosClientId: '672372083867-cnnas3gts1gdvu0shv07j92c4u8dfkq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dano',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDt0BqIpGfmQ53IyS3SEqN0BTXMnQ-JHk',
    appId: '1:672372083867:web:c42a9f8b68f5718f4b0a3e',
    messagingSenderId: '672372083867',
    projectId: 'dano-v2',
    authDomain: 'dano-v2.firebaseapp.com',
    storageBucket: 'dano-v2.firebasestorage.app',
    measurementId: 'G-KW6QGJZJG6',
  );
}
